# Generated by Django 3.1.7 on 2021-03-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quality',
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.DecimalField(choices=[(0, 'new'), (1, 'like_new'), (2, 'good'), (3, 'fair'), (4, 'poor')], decimal_places=0, default=0, max_digits=1),
            preserve_default=False,
        ),
    ]
