# Generated by Django 3.1.7 on 2021-03-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20210307_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Account',
        ),
    ]
