# Generated by Django 3.1.7 on 2021-03-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20210313_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='seller',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.account'),
        ),
    ]
