# Generated by Django 3.1.7 on 2021-03-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.DecimalField(choices=[(0, 'initiated'), (1, 'acknowledged'), (2, 's_pending'), (3, 'b_pending'), (4, 'complete'), (5, 'cancelled')], decimal_places=0, max_digits=1),
        ),
    ]
