# Generated by Django 3.1.7 on 2021-03-27 04:28

import cloudinary.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_auto_20210326_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-03-27', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 3, 27)), django.core.validators.MaxValueValidator(datetime.date(2022, 3, 27))]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='album',
            field=models.ManyToManyField(to='marketplace.Image'),
        ),
    ]
