# Generated by Django 3.1.7 on 2021-04-01 02:46

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_auto_20210327_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contact',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='marketplace.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-04-01', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 4, 1)), django.core.validators.MaxValueValidator(datetime.date(2022, 4, 1))]),
        ),
    ]
