# Generated by Django 3.1.7 on 2021-04-01 04:03

import cloudinary.models
import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_auto_20210331_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('posted_date', models.DateTimeField()),
                ('deadline', models.DateField(help_text='Latest allowed is 2022-04-01', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 4, 1)), django.core.validators.MaxValueValidator(datetime.date(2022, 4, 1))])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('condition', models.DecimalField(choices=[(0, 'New'), (1, 'Like new'), (2, 'Gently-loved'), (3, 'Well-loved'), (4, 'Poor')], decimal_places=0, max_digits=1)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('categories', models.ManyToManyField(to='marketplace.Category')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.account')),
            ],
        ),
    ]
