# Generated by Django 3.1.7 on 2021-04-02 02:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_auto_20210401_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='negotiable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='negotiable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-04-02', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 4, 2)), django.core.validators.MaxValueValidator(datetime.date(2022, 4, 2))]),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-04-02', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 4, 2)), django.core.validators.MaxValueValidator(datetime.date(2022, 4, 2))]),
        ),
    ]
