# Generated by Django 3.1.7 on 2021-04-03 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_auto_20210402_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 15, 48, 42, 210282, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
