# Generated by Django 3.1.7 on 2021-04-11 02:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_auto_20210409_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-04-11', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 4, 11)), django.core.validators.MaxValueValidator(datetime.date(2022, 4, 11))]),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-04-11', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 4, 11)), django.core.validators.MaxValueValidator(datetime.date(2022, 4, 11))]),
        ),
    ]
