# Generated by Django 3.1.7 on 2021-04-16 04:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_auto_20210410_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-04-16', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 4, 16)), django.core.validators.MaxValueValidator(datetime.date(2022, 4, 16))]),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-04-16', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 4, 16)), django.core.validators.MaxValueValidator(datetime.date(2022, 4, 16))]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
