# Generated by Django 3.1.7 on 2021-04-21 00:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_auto_20210417_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(default='tiger-retail.herokuapp.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-04-21', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 4, 21)), django.core.validators.MaxValueValidator(datetime.date(2022, 4, 21))]),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-04-21', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 4, 21)), django.core.validators.MaxValueValidator(datetime.date(2022, 4, 21))]),
        ),
    ]
