# Generated by Django 3.1.8 on 2021-06-16 22:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_auto_20210420_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-06-16', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 6, 16)), django.core.validators.MaxValueValidator(datetime.date(2022, 6, 16))]),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-06-16', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 6, 16)), django.core.validators.MaxValueValidator(datetime.date(2022, 6, 16))]),
        ),
    ]
