# Generated by Django 3.1.8 on 2021-08-03 06:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_auto_20210622_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-08-03', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 8, 3)), django.core.validators.MaxValueValidator(datetime.date(2022, 8, 3))]),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-08-03', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 8, 3)), django.core.validators.MaxValueValidator(datetime.date(2022, 8, 3))]),
        ),
    ]
