# Generated by Django 3.1.8 on 2021-08-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_auto_20210802_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.DecimalField(choices=[(0, 'new'), (1, 'like new'), (2, 'gently loved'), (3, 'well loved'), (4, 'poor')], decimal_places=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='condition',
            field=models.DecimalField(choices=[(0, 'new'), (1, 'like new'), (2, 'gently loved'), (3, 'well loved'), (4, 'poor')], decimal_places=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.DecimalField(choices=[(0, 'initiated'), (1, 'acknowledged'), (2, 'seller pending'), (3, 'buyer pending'), (4, 'complete'), (5, 'cancelled')], decimal_places=0, max_digits=1),
        ),
    ]
