# Generated by Django 3.1.8 on 2021-08-13 01:44

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0030_auto_20210802_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-08-13', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 8, 13)), django.core.validators.MaxValueValidator(datetime.date(2022, 8, 13))]),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='deadline',
            field=models.DateField(help_text='Latest allowed is 2022-08-13', validators=[django.core.validators.MinValueValidator(datetime.date(2021, 8, 13)), django.core.validators.MaxValueValidator(datetime.date(2022, 8, 13))]),
        ),
        migrations.CreateModel(
            name='ItemRequestFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('item_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='marketplace.itemrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='marketplace.item')),
            ],
        ),
    ]
