# Generated by Django 3.1.8 on 2021-08-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0032_auto_20210813_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemflag',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='itemrequestflag',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
